id: 2a76a039-be36-4f7d-9afb-d823660f8a4e
name: Product Launch Q2 25
order: 500
path: /campaign-emails/product-launch-q2-25
type: composition
pathSegment: product-launch-q2-25
data: {}
compositionId: c7987a7a-fec3-4d5f-8096-dffaacbe1ade
projectMapId: 8a35c419-5150-4f76-aa21-7e4976c9dfcb
