/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UniformPlaygroundImport } from './routes/uniform-playground'
import { Route as SubappImport } from './routes/subapp'
import { Route as SplatImport } from './routes/$'

// Create/Update Routes

const UniformPlaygroundRoute = UniformPlaygroundImport.update({
  id: '/uniform-playground',
  path: '/uniform-playground',
  getParentRoute: () => rootRoute,
} as any)

const SubappRoute = SubappImport.update({
  id: '/subapp',
  path: '/subapp',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/subapp': {
      id: '/subapp'
      path: '/subapp'
      fullPath: '/subapp'
      preLoaderRoute: typeof SubappImport
      parentRoute: typeof rootRoute
    }
    '/uniform-playground': {
      id: '/uniform-playground'
      path: '/uniform-playground'
      fullPath: '/uniform-playground'
      preLoaderRoute: typeof UniformPlaygroundImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/subapp': typeof SubappRoute
  '/uniform-playground': typeof UniformPlaygroundRoute
}

export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/subapp': typeof SubappRoute
  '/uniform-playground': typeof UniformPlaygroundRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$': typeof SplatRoute
  '/subapp': typeof SubappRoute
  '/uniform-playground': typeof UniformPlaygroundRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/subapp' | '/uniform-playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/subapp' | '/uniform-playground'
  id: '__root__' | '/$' | '/subapp' | '/uniform-playground'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  SubappRoute: typeof SubappRoute
  UniformPlaygroundRoute: typeof UniformPlaygroundRoute
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  SubappRoute: SubappRoute,
  UniformPlaygroundRoute: UniformPlaygroundRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$",
        "/subapp",
        "/uniform-playground"
      ]
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/subapp": {
      "filePath": "subapp.tsx"
    },
    "/uniform-playground": {
      "filePath": "uniform-playground.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
