name = "uniformedgep13ndemo"
type = "javascript"
zone_id = ""
account_id = "ca9d167d98b5dfa4b400486b6c6794c7"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[vars]
ORIGIN_URL = "nesidemostatic.netlify.app"