composition:
  _name: Home
  _id: 26667348-5cd1-4185-b5a0-8413e1e87117
  _slug: /
  type: page
  parameters:
    metaTitle:
      type: text
      value: Home
  slots:
    content:
      - _id: e52661f5-da9e-4730-b20a-378f452b68d3
        type: $personalization
        slots:
          pz:
            - _id: 7e4625a3-02c3-47c7-b4e3-6f23dc655c85
              type: hero
              parameters:
                title:
                  type: text
                  value: Patagonia vests sale!
                $pzCrit:
                  type: $pzCrit
                  value:
                    crit:
                      - l: spender
                        r: '0'
                        op: '>'
                    name: 'Hero: Patagonia vests sale!'
                description:
                  type: text
                  value: Make sure you are ready your VC meeting!
            - _id: f7acc97e-7233-4e9e-9bab-b061203ba56b
              type: hero
              parameters:
                title:
                  type: text
                  value: Growth marketing!
                $pzCrit:
                  type: $pzCrit
                  value:
                    crit:
                      - l: p_m
                        r: 0
                        op: '>'
                    name: 'Hero: Growth marketing!'
                description:
                  type: text
                  value: Is it a thing?
            - _id: d6d278a7-c5c0-47e8-af45-39a0c8e58abb
              type: hero
              parameters:
                title:
                  type: text
                  value: Let's learn Rust!
                $pzCrit:
                  type: $pzCrit
                  value:
                    crit:
                      - l: p_d
                        r: 0
                        op: '>'
                    name: 'Hero: Let''s learn Rust!'
                description:
                  type: text
                  value: can you build a web page in Rust?
            - _id: 936ab793-84a5-4164-bf2c-113b0e445c9e
              type: hero
              parameters:
                title:
                  type: text
                  value: Hello SF
                $pzCrit:
                  type: $pzCrit
                  value:
                    crit:
                      - l: visitorsFromSf
                        r: '0'
                        op: '>'
                    name: 'Hero: Hello SF'
                description:
                  type: text
                  value: It is 55F and foggy, isn't it?
            - _id: 048ac674-481a-4252-b9c2-c19a98de5cdd
              type: hero
              parameters:
                title:
                  type: text
                  value: We are launched!
                $pzCrit:
                  type: $pzCrit
                  value:
                    crit:
                      - l: launchCampaign
                        r: 0
                        op: '>'
                    name: 'Hero: We are launched!'
                description:
                  type: text
                  value: >-
                    <p>Showing personalized content since "Launch Campaign"
                    signal has a score.</p>
            - _id: e1e9090b-f2c2-4e3f-9015-424e9804e61e
              type: hero
              parameters:
                title:
                  type: text
                  value: Welcome.
                description:
                  type: text
                  value: >-
                    <p>This is default content shown to every visitor. </p>

                    <p>Trigger campaign-based personalization <a
                    href="/?utm_campaign=launch">now</a>!</p>
        parameters:
          count:
            type: number
            value: '1'
          trackingEventName:
            type: text
            value: Home Hero
created: '2022-11-07T04:30:01.340994+00:00'
modified: '2022-11-17T22:55:23.874302+00:00'
pattern: false
