import { UniformContext } from "@uniformdev/canvas-next-rsc";
import { Inter } from "next/font/google";
import Script from "next/script";
import * as snippet from "@segment/snippet";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const renderSnippet = () => {
    const opts = {
      apiKey: process.env.NEXT_PUBLIC_ANALYTICS_WRITE_KEY,
      page: true,
    };
    return process.env.NODE_ENV === "development"
      ? snippet.max(opts)
      : snippet.min(opts);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="main">
          <UniformContext>{children}</UniformContext>
        </main>
      </body>
      <Script
        id="segment-script"
        dangerouslySetInnerHTML={{ __html: renderSnippet() }}
      />
    </html>
  );
}
