export const tealiumData = {
    "site_id": "cherry",
    "site_environment": "production",
    "site_locale": "en-us",
    "site_language": "en",
    "site_country": "US",
    "site_arch": "del",
    "customer_type": "Not Logged In",
    "page_name": "neural",
    "page_type": "PDP",
    "page_category_name": "products",
    "page_subcategory_name": "neural",
    "product_category": "neural",
    "product_brand": "cherrytech",
    "is_mobile_tablet_desktop": "desktop",
    "osType": "Macintosh",
    "cp.utag_main__sn": "3",
    "cp.utag_main__se": "1",
    "cp.utag_main__ss": "1",
    "cp.utag_main__st": "1770266902724",
    "cp.utag_main_ses_id": "1770265102724",
    "cp.utag_main__pn": "1",
    "cp.utag_main_vapi_domain": "cherrytech.com",
    "cp.site_id": "US",
    "cp.LCID": "en-us",
    "cp.OptanonAlertBoxClosed": "2026-02-02T16:03:18.712Z",
    "cp.s_cc": "true",
    "cp.s_ips": "928",
    "cp.s_sq": "[[B]]",
    "cp.s_tp": "6232",
    "cp.s_ppv": "alto-keys-k98m,15,15,928,1,10",
    "cp._meta_main_gtag": "2026-02-05T04:18:22.565Z",
    "dom.referrer": "https://www.cherrytech.com/en-us",
    "dom.title": "Neural - Vision, Ambient | cherrytech",
    "dom.domain": "www.cherrytech.com",
    "dom.query_string": "",
    "dom.hash": "",
    "dom.url": "https://www.cherrytech.com/en-us/shop/c/neural",
    "dom.pathname": "/en-us/shop/c/neural",
    "dom.viewport_height": 612,
    "dom.viewport_width": 1276,
    "ut.domain": "cherrytech.com",
    "ut.version": "ut4.54.202601302108",
    "ut.event": "view",
    "ut.session_id": "1770265102724",
    "ut.account": "cherrytech",
    "ut.profile": "cherry",
    "ut.env": "prod",
    "tealium_event": "view",
    "tealium_session_id": "1770265102724",
    "tealium_session_number": "3",
    "tealium_session_event_number": "1",
    "tealium_datasource": "",
    "tealium_account": "cherrytech",
    "tealium_profile": "cherry",
    "tealium_environment": "prod",
    "tealium_random": "8523319468092481",
    "tealium_library_name": "utag.js",
    "tealium_library_version": "4.54.0",
    "tealium_timestamp_epoch": 1770265102,
    "tealium_timestamp_utc": "2026-02-05T04:18:22.726Z",
    "tealium_timestamp_local": "2026-02-04T20:18:22.726",
    "js_page.document.location.protocol": "https:",
    "js_page.document.location.href": "https://www.cherrytech.com/en-us/shop/c/neural",
    "js_page.document.referrer": "https://www.cherrytech.com/en-us",
    "js_page.userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "js_page.OnetrustActiveGroups": ",C0001,C0002,C0003,",
    "ls.landingTime": "1761627789186",
    "ls.topicsLastReferenceTime": "1765989146839",
    "ls.connection_type_CONNECTION_TYPE_KEY_x1718901280002": "ws",
    "ls.showWelcomeModal": "1",
    "ss.qm_last_page": "https://www.cherrytech.com/en-us/shop/c/neural",
    "ss.qm_last_period": "1770265101916",
    "tci.purposes_with_consent_all": [
        "C0001",
        "C0002",
        "C0003"
    ],
    "tci.consent_type": "explicit",
    "tci.purposes_with_consent_unprocessed": [
        "C0001",
        "C0002",
        "C0003"
    ],
    "tci.purposes_with_consent_processed": [],
    "order_datetime": "undefined|undefined",
    "page_name_nolc": "cherry:undefined",
    "page_name_url": "neural;https://www.cherrytech.com/en-us/shop/c/neural",
    "locale_tealium_extension": "en-us",
    "language": "EN",
    "mcp_id": "f3baaa03c9cecaa9",
    "bv_enabled": 1,
    "_cbrand": "cherrytech",
    "_ccat": "neural",
    "facebook_content_type": "product",
    "bv_locale": "en_US",
    "bv_client_name": "cherrytech-inc",
    "bv_site_id": "main_site"
}