id: launchCampaign
name: Launch Campaign
cap: 100
crit:
  op: '&'
  type: G
  clauses:
    - type: QS
      match:
        cs: false
        op: '='
        rhs: launch
      queryName: utm_campaign
dur: p
description: ''
str: 50
