id: spender
name: Big Spender
cap: 100
crit:
  op: '&'
  type: G
  clauses:
    - key: bigspenders
      type: QK
      match:
        cs: false
        op: '='
        rhs: 'true'
dur: p
description: ''
str: 50
