id: productLaunch
name: Product Launch
cap: 100
crit:
  op: '&'
  type: G
  clauses:
    - type: QS
      match:
        cs: false
        op: '='
        rhs: launch
      queryName: utm_campaign
dur: s
description: ''
str: 50
